//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geometry
{
    [Serializable]
    public class PolygonInstanceMsg : Message
    {
        public const string k_RosMessageName = "geometry_msgs/PolygonInstance";
        public override string RosMessageName => k_RosMessageName;

        //  A specification of a polygon where the first and last points are assumed to be connected
        //  It includes a unique identification field for disambiguating multiple instances
        public PolygonMsg polygon;
        public long id;

        public PolygonInstanceMsg()
        {
            this.polygon = new PolygonMsg();
            this.id = 0;
        }

        public PolygonInstanceMsg(PolygonMsg polygon, long id)
        {
            this.polygon = polygon;
            this.id = id;
        }

        public static PolygonInstanceMsg Deserialize(MessageDeserializer deserializer) => new PolygonInstanceMsg(deserializer);

        private PolygonInstanceMsg(MessageDeserializer deserializer)
        {
            this.polygon = PolygonMsg.Deserialize(deserializer);
            deserializer.Read(out this.id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.polygon);
            serializer.Write(this.id);
        }

        public override string ToString()
        {
            return "PolygonInstanceMsg: " +
            "\npolygon: " + polygon.ToString() +
            "\nid: " + id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
