//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Geometry
{
    [Serializable]
    public class PolygonInstanceStampedMsg : Message
    {
        public const string k_RosMessageName = "geometry_msgs/PolygonInstanceStamped";
        public override string RosMessageName => k_RosMessageName;

        //  This represents a Polygon with reference coordinate frame and timestamp
        //  It includes a unique identification field for disambiguating multiple instances
        public Std.HeaderMsg header;
        public PolygonInstanceMsg polygon;

        public PolygonInstanceStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.polygon = new PolygonInstanceMsg();
        }

        public PolygonInstanceStampedMsg(Std.HeaderMsg header, PolygonInstanceMsg polygon)
        {
            this.header = header;
            this.polygon = polygon;
        }

        public static PolygonInstanceStampedMsg Deserialize(MessageDeserializer deserializer) => new PolygonInstanceStampedMsg(deserializer);

        private PolygonInstanceStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.polygon = PolygonInstanceMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.polygon);
        }

        public override string ToString()
        {
            return "PolygonInstanceStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\npolygon: " + polygon.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
