//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PreprocessedRobot
{
    [Serializable]
    public class ObservationMsg : Message
    {
        public const string k_RosMessageName = "preprocessed_robot_msgs/Observation";
        public override string RosMessageName => k_RosMessageName;

        public int n_obs;
        public float[] obs;
        public bool terminated;

        public ObservationMsg()
        {
            this.n_obs = 0;
            this.obs = new float[0];
            this.terminated = false;
        }

        public ObservationMsg(int n_obs, float[] obs, bool terminated)
        {
            this.n_obs = n_obs;
            this.obs = obs;
            this.terminated = terminated;
        }

        public static ObservationMsg Deserialize(MessageDeserializer deserializer) => new ObservationMsg(deserializer);

        private ObservationMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.n_obs);
            deserializer.Read(out this.obs, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.terminated);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.n_obs);
            serializer.WriteLength(this.obs);
            serializer.Write(this.obs);
            serializer.Write(this.terminated);
        }

        public override string ToString()
        {
            return "ObservationMsg: " +
            "\nn_obs: " + n_obs.ToString() +
            "\nobs: " + System.String.Join(", ", obs.ToList()) +
            "\nterminated: " + terminated.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
